---
title: "Co-flowering and hummingbird overlap in Neotropical Gesneriaceae: Phylogeny and Interactions"
author: "Ben Weinstein"
date: "5/30/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r,message=F,warning=F}
library(knitr)
opts_chunk$set(message=F,warning=F,echo=F)

library(ape)
library(ggbiplot)
library(kableExtra)
library(boot)
library(dplyr)
library(ggplot2)
library(phytools)
library(stringr)
library(splines)
library(R2jags)
library(reshape2)
library(tidyr)
```

# Interactions

```{r}
#Interactions
interactions<-read.csv("data/cleaned/interactions_all.csv",row.names=1)
# to_keep<-interactions %>% group_by(Plant) %>% summarize(n=length(unique(ID))) %>% arrange(n) %>% filter(n>3) %>% .$Plant
# interactions<-interactions %>% filter(Plant %in% to_keep) %>% droplevels()

gesner<-c("Columnea ciliata","Columnea kucyniakii","Drymonia tenuis","Columnea mastersonii","Gasteranthus quitensis","Drymonia teuscheri",
  "Columnea strigosa","Glossoloma oblongicalyx","Gasteranthus lateralis","Kohleria affinis","Besleria solanoides","Drymonia brochidodroma",
  "Drymonia collegarum","Alloplectus purpuruem","Columnea picta","Kohleria villosa","Columnea medicinalis","Glossoloma purpureum",
  "Kohleria spicata")

interactions<-interactions %>% filter(Plant %in% gesner) %>% droplevels()
#Just the more common plants
head(interactions) %>% kable() %>% kable_styling()
```

# Estimate interaction probability

```{r}
#Convert to binary daily sampling
dailydat<-interactions %>% group_by(ID,Date,Plant,Hummingbird) %>% summarize(Yobs=n())

#Impute non-detections. Start by assuming all hummingbirds occur at all elevations (can be relaxed)

sumf<-dailydat %>% group_by(Plant,ID,Date) %>% summarize(Yobs=sum(Yobs))

#Create emptys zeros
impute_zero<-function(x,Hummingbird){
  df<-data.frame(Hummingbird=Hummingbird)
}

zero_count<-sumf %>% group_by(Plant,ID,Date) %>% do(impute_zero(.,Hummingbird=levels(dailydat$Hummingbird)))
zero_count<-zero_count %>% anti_join(dailydat)

#add a dummy label for presence absence
indat<-bind_rows(data.frame(dailydat),data.frame(zero_count,Yobs=0))
```

```{r}
#Easiest to work with jags as numeric ordinal values
indat$Hummingbird<-as.factor(indat$Hummingbird)
indat$Plant<-as.factor(indat$Plant)
indat$jBird<-as.numeric(indat$Hummingbird)
indat$jPlant<-as.numeric(indat$Plant)

jagsIndexBird<-data.frame(Hummingbird=levels(indat$Hummingbird),jBird=factor(1:length(levels(indat$Hummingbird))))
jagsIndexPlants<-data.frame(Plant=levels(indat$Plant),jPlant=factor(1:length(levels(indat$Plant))))

indat$Index<-1:nrow(indat)
indat<-droplevels(indat)

#Turn Time and ID into numeric indexes
indat$jTime<-as.numeric(as.factor(indat$Date))
indat$jID<-as.numeric(as.factor(indat$ID))

```

```{r}
#hold model objects
models<-list()
chains<-list()
```

```{r}
#Source model
source("model/poisson_interactions.R")

#print model
writeLines(readLines("model/poisson_interactions.R"))

#Run Model
runModel<-function(Yobs_dat){
  
  #Parameters to track
  ParsStage <- c("lambda","omega")
  
  InitStage<-function(){
      z = array(dim=c(max(Yobs_dat$jBird),max(Yobs_dat$jPlant),max(Yobs_dat$jID)),data=max(Yobs_dat$Yobs)+1)
      return(list(z=z))
  }
  #Jags Data

  Dat<-list(
    Yobs=Yobs_dat$Yobs,
    Birds=max(c(Yobs_dat$jBird)),
    Bird=Yobs_dat$jBird,
    Plant=Yobs_dat$jPlant,
    Cameras=max(Yobs_dat$jID),
    Camera=Yobs_dat$jID,
    Plants=max(c(Yobs_dat$jPlant)),
    Nobs=length(Yobs_dat$Yobs))
  
  #MCMC options
    system.time(
      model<-jags(data=Dat, parameters.to.save=ParsStage,model.file="model/poisson_interactions.jags",n.thin=2,n.iter=5000,n.burnin=4000,inits=InitStage,n.chains=2,DIC=F)
    )
    return(model)
}

models$intercept<-runModel(Yobs_dat=indat)
```

View Chains

```{r}
getChains<-function(mod){
  
  pc<-reshape2::melt(mod$BUGSoutput$sims.array)
  colnames(pc)<-c("Draw","chain","par","value")
  
  #extract parameter name
  pc$parameter<-data.frame(str_match(pc$par,"(\\w+)"))[,-1]
  
  #Extract index
  splitpc<-split(pc,pc$parameter)
  
  #   #single index
  # splitpc[c("omega")]<-lapply(
  #   splitpc[c("omega")],function(x){
  #   sv<-data.frame(str_match(x$par,"(\\w+)\\[(\\d+)"))[,3]
  #   pc<-data.frame(x,jBird=sv)
  #   })
  
  #double index
  splitpc[c("lambda")]<-lapply(
    splitpc[c("lambda")],function(x){
    sv<-data.frame(str_match(x$par,"(\\w+)\\[(\\d+),(\\d+)]"))[,3:4]
    colnames(sv)<-c("jBird","jPlant")
    pc<-data.frame(x,sv)
    })
  
  chains<-bind_rows(splitpc)
return(chains)}
```

```{r,fig.height=8,fig.width=12}
chains$intercept<-getChains(models$intercept)

#merge species names
chains$intercept<-chains$intercept %>% left_join(jagsIndexBird) %>% left_join(jagsIndexPlants)

#alpha
chains$intercept %>% filter(parameter %in% "lambda",jPlant %in% c(5,10)) %>% ggplot(.,aes(x=value,fill=Plant)) + geom_histogram() + facet_wrap(~Hummingbird,scales="free")
```

### I(Interaction)

```{r,fig.height=8,fig.width=8}
chains$intercept %>% filter(parameter %in% "lambda") %>% group_by(Hummingbird,Plant) %>% summarize(n=mean(value)) %>% ggplot(.,aes(fill=n,x=Plant,y=Hummingbird)) + geom_tile() + theme(axis.text.x = element_text(angle=-90)) + labs(fill="P(Interaction)") + scale_fill_gradient2(low="white",mid="blue",high="Red",midpoint=1,limits=c(0,3))
```

# Niche Overlap

Euclidean Distance in the Intensity of Interaction

```{r}
alpha_matrix<-chains$intercept %>% filter(parameter %in% "lambda") %>% group_by(Hummingbird,Plant) %>% summarize(n=mean(value)) %>% acast(Hummingbird~Plant)
write.csv(alpha_matrix,"data/Interaction_Intensity.csv")
```

```{r}
ggbiplot(prcomp(t(alpha_matrix)),labels = colnames(alpha_matrix),varname.size = 2) + coord_cartesian(xlim=c(-2.5,2.5),ylim=c(-2.5,2.5))
ggsave("Figures/biplot_labels.svg",height=6,width=8)
ggbiplot(prcomp(t(alpha_matrix)))+ coord_cartesian(xlim=c(-2.5,2.5),ylim=c(-2.5,2.5))
ggsave("Figures/biplot.svg",height=6,width=8)
```
